### ISSUE TITLE
`frozenset` was available in V1 and will be available in V2 from v2.1.1

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-stubs#84]
From:
- https://github.com/microbit-foundation/micropython-microbit-v2/issues/138#issuecomment-1288941848

**Comment by microbit-matt-hillsdon** [comment]
Thanks. When we upgrade, we can revert the relevant subset of 8a20c2f2d90b4932530bcba0c77db9e4aa01ff1c (though we'll need to check what methods it actually has in MicroPython).

**Comment by microbit-matt-hillsdon** [comment]
This was addressed back in https://github.com/microbit-foundation/micropython-microbit-stubs/pull/85
