### ISSUE TITLE
Update to the `Image.SMILE` description

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-stubs#98]
Reported by @microbit-lucy from a support ticket.

`Image.SMILE` only includes the mounth:
![A6E4E396-00BB-4181-8AD7-59E3B79CFBFE](https://github.com/microbit-foundation/micropython-microbit-stubs/assets/29712657/08aee94c-f966-46e3-b98a-5f4145c4e6eb)

So we might update the description to something like "Smiling mouth image" (originally suggested by @jaustin):
![74B8ACDD-3CA7-41A7-8CFE-089133F8FC3B](https://github.com/microbit-foundation/micropython-microbit-stubs/assets/29712657/d0822246-5271-4192-8023-e2235430ca86)

@microbit-grace is this something you could look into?

**Comment by microbit-robert** [comment]
This is now on beta and will be included in the next release. Thanks @microbit-grace.
